// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';

import 'src/features/todo/domain/todo.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 7518507964579897803),
      name: 'TodoObject',
      lastPropertyId: const IdUid(4, 8885010377169335998),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4302652518345005053),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 4193615595503789332),
            name: 'completed',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 3301216807021751571),
            name: 'title',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Store openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) =>
    Store(getObjectBoxModel(),
        directory: directory,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 7518507964579897803),
      lastIndexId: const IdUid(2, 5170710850679797905),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [1974739057549059059, 5170710850679797905],
      retiredPropertyUids: const [8885010377169335998],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    TodoObject: EntityDefinition<TodoObject>(
        model: _entities[0],
        toOneRelations: (TodoObject object) => [],
        toManyRelations: (TodoObject object) => {},
        getId: (TodoObject object) => object.id,
        setId: (TodoObject object, int id) {
          object.id = id;
        },
        objectToFB: (TodoObject object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addBool(1, object.completed);
          fbb.addOffset(2, titleOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = TodoObject(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              completed:
                  const fb.BoolReader().vTableGet(buffer, rootOffset, 6, false),
              title: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [TodoObject] entity fields to define ObjectBox queries.
class TodoObject_ {
  /// see [TodoObject.id]
  static final id =
      QueryIntegerProperty<TodoObject>(_entities[0].properties[0]);

  /// see [TodoObject.completed]
  static final completed =
      QueryBooleanProperty<TodoObject>(_entities[0].properties[1]);

  /// see [TodoObject.title]
  static final title =
      QueryStringProperty<TodoObject>(_entities[0].properties[2]);
}
